# Generated by Django 3.1.5 on 2021-01-25 20:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('project_description', models.TextField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('notes', models.TextField(max_length=500)),
                ('date_added', models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 25, 20, 47, 3, 727460, tzinfo=utc))),
                ('scheduled_done', models.DateField()),
                ('status', models.CharField(choices=[('Done', 'Done'), ('In Progress', 'In Progress'), ('Next Up', 'Next Up'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('priority', models.CharField(choices=[('1', 'Highest'), ('2', 'Medium'), ('3', 'Low'), ('4', 'Not Important')], default='4', max_length=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('task_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
    ]
