# Generated by Django 3.1.5 on 2021-01-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'High'), ('2', 'Medium'), ('3', 'Low'), ('4', 'Not Important')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='scheduled_done',
            field=models.DateField(verbose_name='Scheduled to be done by:'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('In Progress', 'In Progress'), ('Stuck', 'Stuck'), ('Next Up', 'Next Up'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=200, verbose_name='Task Title'),
        ),
    ]
